# Generated by Django 5.2.7 on 2025-11-14 23:00

from django.db import migrations

def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('home', 'Profile')
    
    # วนลูป User ทุกคนในระบบ
    for user in User.objects.all():
        # บรรทัดนี้จะถูกย่อหน้าเข้ามาอีกระดับ เพราะอยู่ภายใน for loop
        Profile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
    ]
