# Generated by Django 5.2.7 on 2025-12-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_create_profiles_for_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_mascot',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
